apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
        - name: catalog-container
          image: cloud-project-catalog
          ports:
            - containerPort: 3001
          readinessProbe:
            httpGet:
              path: /healthz   # Adjust this path to your application's health check endpoint
              port: 3001      # Port on which your application listens for health checks
          volumeMounts:
            - name: catalog-volume
              mountPath: /catalog  # Adjust the mount path as needed
      volumes:
        - name: catalog-volume
          emptyDir: {}
