apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-app
  template:
    metadata:
      labels:
        app: catalog-app
    spec:
      containers:
        - name: catalog
          image: cloud-project_catalog:latest
          ports:
            - containerPort: 3001
          volumeMounts:
            - name: catalog-pub
              mountPath: /catalog/catalog_style
            - name: catalog-views
              mountPath: /catalog/catalogPage
      volumes:
        - name: catalog-pub
          hostPath:
            path: ./catalog/catalog_style
        - name: catalog-views
          hostPath:
            path: ./catalog/catalogPage
