version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 20201700558
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d
    networks:
      - mynetwork

  reg-log:
    build: ./login-register
    container_name: reg-log-container
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    volumes:
      - ./login-register/login_register_pages:/register-login/login_register_pages
  
  catalog:
    build: ./catalog
    container_name: catalog-container
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3001:3001"
    networks:
      - mynetwork
    volumes:
      - ./catalog/catalog_style:/catalog/catalog_style
      - ./catalog/catalogPage:/catalog/catalogPage

  cart:
    build: ./cart
    container_name: cart-container
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3002:3002"
    networks:
      - mynetwork
    volumes:
      - ./cart/cartImages_style:/cart/cartImages_style
      - ./cart/cartPage_checkoutPage:/cart/cartPage_checkoutPage

networks:
  mynetwork:
