FROM node

WORKDIR /cart

ADD cartServer.js .
ADD package.json .
ADD package-lock.json .
ADD cartImages_style ./cartImages_style
ADD cartPage_checkoutPage ./cartPage_checkoutPage

# Install postgres client tool using npm
RUN npm install pg


# Install other Node.js dependencies
RUN npm install express body-parser

# Expose port
EXPOSE 3002

# Command to run the application
CMD [ "npm", "start" ]