FROM node

WORKDIR /cart

ADD server.js .
ADD package.json .
ADD package-lock.json .
ADD public ./public
ADD views ./views
ADD images ./images
# Install postgres client tool using npm
RUN npm install pg


# Install other Node.js dependencies
RUN npm install express body-parser

# Expose port
EXPOSE 3002

# Command to run the application
CMD [ "npm", "start" ]